name: chegg
description: chegg project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  # environment related
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  fluttertoast: ^8.0.8
  provider: ^6.0.1
  location: ^4.3.0
  rxdart: ^0.27.3
  #  connectivity: ^3.0.6
  shared_preferences: ^2.0.11
  flutter_bloc: ^8.0.0
  #  firebase_messaging: ^9.1.4
  flutter_form_builder: ^7.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  cloud_firestore:
  firebase_auth:
  device_preview: ^1.0.0
  pull_to_refresh: ^2.0.0
  flutter_share: ^2.0.0
  url_launcher: ^6.1.7

  dio: ^4.0.4
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Service locator
  get_it: ^7.2.0
  # Swap the connectivity package for this
  connectivity_plus: ^2.1.0
  # for dependency injection
  injectable: ^1.5.0
  # Svg
  flutter_svg: ^1.0.1
  timelines: ^0.1.0
  # display signature
  signature: ^5.0.0
  # save signature
  permission_handler: ^9.2.0
  #  image_gallery_saver: ^1.7.1
  image_cropper: ^2.0.3
  flag: ^6.0.0


  #  multi_select_flutter: ^4.0.0
  # show snackbar
  flushbar: ^1.10.4
  persistent_bottom_nav_bar:
    path: lib/core/ui/widget/persistent_bottom_nav_bar
  flutter_scrolling_fab_animated: ^0.1.3+2
  flutter_barcode_scanner: ^2.0.0
  gallery_saver: ^2.3.2
  path: ^1.6.4
  flutter_file_manager: any
  #  path_provider_ex: ^1.0.1
  image_picker: ^0.8.5
  nb_utils: ^4.5.2
  pay: ^1.0.9
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  #  double_back_to_close_app: ^2.0.1
  flutter_typeahead: ^4.0.0
  flutter_screenutil: ^5.0.2
  flutter_native_splash: ^2.2.0+1
  google_geocoding: ^0.2.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  change_app_package_name: ^1.0.0
  flutter_phoenix: ^1.0.0
  video_player: ^2.3.0

flutter_native_splash:
  color: "#181820"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  #test: any
  mockito: any
  moor_generator:
  flutter_launcher_icons: ^0.11.0
  injectable_generator: ^1.5.2
  file_picker: ^4.3.0
  webview_flutter: ^3.0.0
  font_awesome_flutter: ^10.1.0
  badges: ^2.0.3



  build_runner:

# environment related
flutter_icons:
  android: "logo"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/home/svg/
    - assets/images/navigation/png/
    - assets/images/navigation/svg/
    - assets/images/account/svg/
    - assets/images/setting/svg/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
        - weight: 300
  # localization
  generate: true

flutter_intl:
  enabled: true
